CREATE TABLE PRODUCT (
   PRODUCTID TEXT PRIMARY KEY,
   PRODUCT_NAME VARCHAR(255),
   PRODUCT_PRICE VARCHAR(255),
   QUANTITY VARCHAR(255)
);

CREATE TABLE PRODUCT_ORDER (
   ID INT PRIMARY KEY,
   NAME VARCHAR(255),
   PRICE VARCHAR(255),
   ORDER_PRODUCT_ID VARCHAR(255),
   QUANTITY VARCHAR(255),
   TOTAL INT
      
);